[package]
name = "Modal-and-Nodal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thirtyfour = "0.26.0"
tokio = { version = "1", features = ["full"] }
color-eyre = "0.6"